init:
  - git config --global core.autocrlf input

services:
  - postgresql

install:
  - choco install strawberryperl --version 5.20.1.1 -y --allow-empty-checksums
  - SET PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
  - cpanm -n App::cpm

build: off

test_script:
  - cpm install -v 

cache:
  - local_action

shallow_clone: true